### ISSUE TITLE
InvalidOperationException with multiple Spark instances

### ISSUE THREAD

**Issue by rorourke-iot** [darrenparkinson/SparkDotNet#7]
When attempting to test using multiple instances of the Spark class, I received the following exception:

System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at SparkDotNetTester.Program.Main(String[] args) in C:\Projects\Test\SparkDotNetTester\Program.cs:line 15
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233079
       Message=This instance has already started one or more requests. Properties can only be modified before sending the first request.
       Source=System.Net.Http
       StackTrace:
            at System.Net.Http.HttpClient.CheckDisposedOrStarted()
            at System.Net.Http.HttpClient.set_BaseAddress(Uri value)
            at SparkDotNet.Spark..ctor(String accessToken)
            at SparkDotNetTester.Program.<RunAsyncBot>d__3.MoveNext() in C:\Projects\Test\SparkDotNetTester\Program.cs:line 47
       InnerException: 

with the following code (error occurs on RunAsynchBot line).

`    static void Main(string[] args)
    {
      RunAsync().Wait();
      RunAsyncBot().Wait();
      Console.ReadKey();
    }

    static string _testRoomId = "<room id>";

    static async Task RunAsync()
    {
      var myToken = "<personal token>";
      var spark = new Spark(myToken);
      Console.WriteLine(await spark.CreateMessageAsync(_testRoomId, text: "Let's do this"));
    }

    static async Task RunAsyncBot()
    {
      var botToken = "<bot token>";
      var sparkBot = new Spark(botToken);
      Console.WriteLine(await sparkBot.CreateMessageAsync(_testRoomId, text: "If you insist"));
    }
`
When I pull the code for SparkDotNet into a separate project and replace the reference with the new local version, it exception does not occur. I'm assuming I built the local version incorrectly to somehow deviate from the build in Nuget.

Windows 10
.NET Framework 4.6.1 (Windows 10 Anniversary Update)
Visual Studio 2015

Thoughts?

**Comment by darrenparkinson** [comment]
Hi, thanks for the message.  Yes, I think it is due to the information in [Issue 4](https://github.com/darrenparkinson/SparkDotNet/issues/4).  The nuget package is a couple of commits behind the repo.  I'm hoping to update that soon.  I was hoping to get another couple of features in before  I did, but I can update it sooner if necessary?

**Comment by rorourke-iot** [comment]
Ahh. That's fine. I don't think I need the library immediately (I'm doing preliminary testing of different solution paths), but did want to make you aware of the issue I experienced. I have a short-term workaround. Thanks for the feedback. Looking forward to the next update.

**Comment by darrenparkinson** [comment]
OK great.  Feel free to reach out with other requests as required.  Are you ok for me to close this issue?

**Comment by rorourke-iot** [comment]
Yes. I think closing it is the good way to go. Appreciate looking into it.
